### ISSUE TITLE
Board files are saved to disk on repl it, making them as public as the instance

### ISSUE THREAD

**Issue by francisduvivier** [francisduvivier/aoc-discord-notifier-bot#15]
Just opening this issue, so that this is clear and so that people that care about this can let me know so that I know it's worth improving.

**Comment by cuscada** [comment]
But I guess if we disable this saving JSON feature, there will be a huge backlash like the removal of rank change detection, is it?

**Comment by francisduvivier** [comment]
Only if the program would be killed and restarted.
But the idea would be to put a flag for that in an environment variable and
add a repl config so that the file saving is disabled by default only on on
replit.

**Comment by cuscada** [comment]
Oh, I found an easy workaround. Maybe you need to add in the README, to put `onBoot="rm -f data/*.json"` on the `.replit` file to delete the JSON file every time the repl activates. Therefore any fork to the repl will not reveal the sensitive JSON data of that private leaderboard.

EDIT:
I had it tested [here](https://repl.it/@grrlic/aoclb-js#.replit)

**Comment by francisduvivier** [comment]
Ah that's interesting, but then the files would still be there while it's running, so I'd want to disable file saving completely on replit

**Comment by cuscada** [comment]
Oh, I see.. But imho that effort is not that worth it, especially for Replit unless you share the repl (multiplayer feature), other people will start a new Repl session, and hence with that trick the sensitive json will get deleted (even though the repl owner is currently running the code at that exact seconds).

But again, that's up to you :D
